version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "5432:5432"
    environment:
      - SA_PASSWORD=MyStrongPassword169.
      - ACCEPT_EULA=Y
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - mynetwork

  alembic:
    build:
      context: ./
      dockerfile: migrations/Dockerfile
    container_name: alembic
    depends_on:
      - db
    command: >
      sh -c "
      alembic upgrade head && echo 'Migrations applied successfully.'
      "
    restart: "on-failure"

  content_api:
    build:
      context: ./
      dockerfile: api/content_api/Dockerfile
    container_name: content_api
    depends_on:
      - db
      - alembic
    ports:
      - "8001:8001"
    volumes:
      - ./:/app/
    command: >
      sh -c "
      uvicorn api.content_api.main:app --host 0.0.0.0 --port 8001 --reload
      "
  identity_api:
    build:
      context: ./
      dockerfile: api/identity_api/Dockerfile
    container_name: identity_api
    depends_on:
      - db
      - alembic
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    command: >
      sh -c "
      uvicorn api.identity_api.main:app --host 0.0.0.0 --port 8000 --reload
      "
  people_api:
    build:
      context: ./
      dockerfile: api/people_api/Dockerfile
    container_name: people_api
    depends_on:
      - db
      - alembic
    ports:
      - "8002:8002"
    volumes:
      - ./:/app/
    command: >
      sh -c "
      uvicorn api.people_api.main:app --host 0.0.0.0 --port 8002 --reload
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: >
      sh -c "
      npm install && npm start
      "

volumes:
  sqlserver_data:

networks:
  mynetwork:
