version: "3.9"

services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  alembic:
    build:
      context: ./
      dockerfile: migrations/Dockerfile
    container_name: alembic
    depends_on:
      - db
    environment:
      - PG_DSN=${PG_DSN}
      - DATABASE=POSTGRES
    command: >
      sh -c "
      alembic upgrade head && echo 'Migrations applied successfully.'
      "
    restart: "on-failure"

  api:
    build:
      context: ./
      dockerfile: api/Dockerfile
    container_name: fastapi
    depends_on:
      - db
      - alembic
    environment:
      - PG_DSN=${PG_DSN}
      - DATABASE=POSTGRES
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    command: >
      sh -c "
      uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  postgres_data:

networks:
  default:
    name: ttsaw_network
