version: "3.9"

services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  alembic:
    build:
      context: ./
      dockerfile: migrations/Dockerfile
    container_name: alembic
    depends_on:
      - db
    environment:
      - PG_DSN=${PG_DSN}
      - DATABASE=POSTGRES
    command: >
      sh -c "
      alembic upgrade head && echo 'Migrations applied successfully.'
      "
    restart: "on-failure"

  content_api:
    build:
      context: ./
      dockerfile: api/content_api/Dockerfile
    container_name: content_api
    depends_on:
      - db
      - alembic
    environment:
      - PG_DSN=${PG_DSN}
      - DATABASE=POSTGRES
    ports:
      - "8001:8001"
    volumes:
      - ./:/app/
    command: >
      sh -c "
      uvicorn api.content_api.main:app --host 0.0.0.0 --port 8001 --reload
      "
  identity_api:
    build:
      context: ./
      dockerfile: api/identity_api/Dockerfile
    container_name: identity_api
    depends_on:
      - db
      - alembic
    environment:
      - PG_DSN=${PG_DSN}
      - DATABASE=POSTGRES
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    command: >
      sh -c "
      uvicorn api.identity_api.main:app --host 0.0.0.0 --port 8000 --reload
      "
  people_api:
    build:
      context: ./
      dockerfile: api/people_api/Dockerfile
    container_name: people_api
    depends_on:
      - db
      - alembic
    environment:
      - PG_DSN=${PG_DSN}
      - DATABASE=POSTGRES
    ports:
      - "8002:8002"
    volumes:
      - ./:/app/
    command: >
      sh -c "
      uvicorn api.people_api.main:app --host 0.0.0.0 --port 8002 --reload
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: >
      sh -c "
      npm install && npm start
      "

volumes:
  postgres_data:

networks:
  default:
    name: ttsaw_network
